# Generated by Django 3.1.5 on 2021-01-19 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210119_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 19, 13, 40, 43, 175707)),
        ),
    ]
